name: note_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0-113.1.beta

dependencies:
  font_awesome_flutter: ^11.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # ضفت لك المكتبة دي عشان لو حبيت تستخدم أيقونات SVG زي اللي بعتها
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 1. قسم الصور والأيقونات (Assets)
  assets:
  #  - assets
    # - assets/icons/telegram_outline.svg

  # 2. قسم الخطوط (Fonts)
  # تأكد من وجود الملف في assets/fonts/Montserrat-Regular.ttf
  fonts:
    - family: MontserratSemi
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
